import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "@/app/styles/reset.scss";
import "@/app/styles/globals.scss";
import Header from "@/app/components/layout/header";
import ScrollContainer from "./components/layout/scroll-container";

const NotoSansKR = Noto_Sans_KR({
    variable: "--font-noto-sans-kr",
    preload: false,
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${NotoSansKR.variable}`}>
                <div className="wrap">
                    <Header />
                    <ScrollContainer>{children}</ScrollContainer>
                </div>
            </body>
        </html>
    );
}
