import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import Header from "@/app/components/layout/header";
import ScrollContainer from "./components/layout/scroll-container";
import { Suspense } from "react";
import "@/app/styles/reset.scss";
import "@/app/styles/globals.scss";

const notoSansKR = Noto_Sans_KR({
    variable: "--font-noto-sans-kr",
    weight: ["100", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${notoSansKR.variable}`}>
                <div className="wrap">
                    <Header />
                    <Suspense fallback={<div>Loading...</div>}>
                        <ScrollContainer>{children}</ScrollContainer>
                    </Suspense>
                </div>
            </body>
        </html>
    );
}
